# YOLOv5 🚀 by Ultralytics, GPL-3.0 license

# Parameters
nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# Densenet121 backbone
backbone:
  # [from, number, module, args]
  [
    [-1, 1, Densenet121, [64, 0, "densenet_input"]],  # 0-P1/2  arg[0] = c_out
   [-1, 1, Densenet121, [256, 0, "densenet_layer"]],  # 1-P2/4
   [-1, 1, Densenet121, [128, 0, "densenet_transition_layer"]],

   [-1, 1, Densenet121, [512, 1, "densenet_layer"]],  # out
   [-1, 1, Densenet121, [256, 1, "densenet_transition_layer"]],

   [-1, 1, Densenet121, [1024, 2, "densenet_layer"]],  # out
   [-1, 1, Densenet121, [512, 2, "densenet_transition_layer"]],

   [-1, 1, Densenet121, [1024, 3, "densenet_layer"]],  #

   [-1, 1, SPPF, [1024, 5]],  # 8
  ]

# YOLOv5 v6.0 head
head:
  [
    [ -1, 1, Conv, [ 512, 1, 1 ] ],
    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 5 ], 1, Concat, [ 1 ] ],  # cat backbone P4
    [ -1, 3, C3, [ 512, False ] ],  # 13

    [ -1, 1, Conv, [ 256, 1, 1 ] ],
    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 3 ], 1, Concat, [ 1 ] ],  # cat backbone P3
    [ -1, 3, C3, [ 256, False ] ],  # 17 (P3/8-small)

    [ -1, 1, Conv, [ 256, 3, 2 ] ],
    [ [ -1, 13 ], 1, Concat, [ 1 ] ],  # cat head P4
    [ -1, 3, C3, [ 512, False ] ],  # 20 (P4/16-medium)

    [ -1, 1, Conv, [ 512, 3, 2 ] ],
    [ [ -1, 9 ], 1, Concat, [ 1 ] ],  # cat head P5
    [ -1, 3, C3, [ 1024, False ] ],  # 23 (P5/32-large)

   [[16, 19, 22], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
