# YOLOAir 🚀 by 🥭, GPL-3.0 license

# Parameters
nc: 80  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLO backbone
# 96[96, 192, 384, 768]
backbone:
  [[-1, 1, HorNet, [32, 0, 3, [2, 3, 18, 2], 32]],
   [-1, 1, HorNet, [64, 1, 3, [2, 3, 18, 2], 32]],
   [-1, 1, HorNet, [128, 2, 3, [2, 3, 18, 2], 32]],
   [-1, 1, HorNet, [256, 3, 3, [2, 3, 18, 2], 32]],
  ]

# YOLOv5 head
head:
  [[-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 2], 1, Concat, [1]],
   [-1, 3, C3, [256, False]],

   [-1, 1, Conv, [128, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 1], 1, Concat, [1]],
   [-1, 3, C3, [128, False]],

   [-1, 1, Conv, [128, 3, 2]],
   [[-1, 8], 1, Concat, [1]],
   [-1, 3, C3, [256, False]],

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 4], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [256, False]],  # 23 (P5/32-large)

   [[11, 14, 17], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]

