# Parameters
nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple
anchors: 1  # number of anchors
loss: ComputeXLoss

# YOLOv5 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, ConvNextBlock, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, ConvNextBlock, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, ConvNextBlock, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 3, ConvNextBlock, [1024]],  # 9
  ]

# YOLOv5 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

# yolox head
   [17, 1, Conv, [256, 1, 1]],  # 24 lateral0 (P3/8-small)
   [20, 1, Conv, [256, 1, 1]],  # 25 lateral1 (P4/16-medium)
   [23, 1, Conv, [256, 1, 1]],  # 26 lateral2 (P5/32-large)

   [24, 2, Conv, [256, 3, 1]],  # 27 cls0 (P3/8-small)
   [24, 2, Conv, [256, 3, 1]],  # 28 reg0 (P3/8-small)

   [25, 2, Conv, [256, 3, 1]],  # 29 cls1 (P4/16-medium)
   [25, 2, Conv, [256, 3, 1]],  # 30 reg1 (P4/16-medium)

   [26, 2, Conv, [256, 3, 1]],  # 31 cls2 (P5/32-large)
   [26, 2, Conv, [256, 3, 1]],  # 32 reg2 (P5/32-large)

    [[27, 28, 29, 30, 31, 32], 1, DetectX, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
