# YOLOX 🚀

# Parameters
nc: 80  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple
anchors: 1  # number of anchors
loss: ComputeXLoss

# YOLO backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 1, SimAM, [512]], #  9 update
   [-1, 3, BoT3, [1024]],  # 10
  ]

# YOLOX head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 14

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 18 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 15], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 21 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 11], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 24 (P5/32-large) 

   [17, 1, Conv, [256, 1, 1]],  # 25  (P3/8-small)
   [20, 1, Conv, [256, 1, 1]],  # 26  (P4/16-medium)
   [23, 1, Conv, [256, 1, 1]],  # 27  (P5/32-large)

   [25, 2, Conv, [256, 3, 1]],  # 28 cls0 (P3/8-small)
   [25, 2, Conv, [256, 3, 1]],  # 29 reg0 (P3/8-small)

   [26, 2, Conv, [256, 3, 1]],  # 30 cls1 (P4/16-medium)
   [26, 2, Conv, [256, 3, 1]],  # 31 reg1 (P4/16-medium)

   [27, 2, Conv, [256, 3, 1]],  # 32 cls2 (P5/32-large)
   [27, 2, Conv, [256, 3, 1]],  # 33 reg2 (P5/32-large)

    [[28, 29, 30, 31, 32, 33], 1, DetectX, [nc, anchors]],  # DetectX(P3, P4, P5)
  ]
